### ISSUE TITLE
Neptune Beta 5 issue

### ISSUE THREAD

**Issue by fatlind08** [duraidabdul/Neptune#39] opened 2019-02-21 23:11 UTC
Hi i installed The Beta 5 on my iPhone 8 Plus but the lockscreen Shortcuts did not work.

Have a nice Day/Night

**Comment by fatlind08** [comment] 2019-02-21 23:13
And the bar at the bottom does just appear in the Lockscreen

**Comment by duraidabdul** [comment] 2019-02-21 23:41
Duplicate of #16

**Closed as completed by duraidabdul** 2019-02-21 23:41 UTC
