### ISSUE TITLE
Can You Add A Unlocked Indicator in the lock screen like Face ID

### ISSUE THREAD

**Issue by X-Corde** [duraidabdul/Neptune#25] opened 2019-02-12 00:52 UTC
I'd like to see the update of the lock screen that is about the locked indicator, if you have unlocked with  touch id, the indicator will change to unlock, if you add it, it will look more like iPhone x does, thanks.
Plus, you guys are amazing.

**Comment by duraidabdul** [comment] 2019-02-12 03:23
Duplicate of #24

**Closed as completed by duraidabdul** 2019-02-12 03:23 UTC
