### ISSUE TITLE
Installing Uncover Cydia

### ISSUE THREAD

**Issue by hackerdr** [duraidabdul/Neptune#52] opened 2019-02-23 06:36 UTC
How can I install this with cydia ? Where is the repo source ? I have tried to install with geofilza but it says command not found.

**Comment by teelekkung** [comment] 2019-02-23 07:09
Duplicate of 45#

**Comment by addtheryan** [comment] 2019-02-23 11:58
Yes same on me
bash: Filza: command not found

**Comment by teelekkung** [comment] 2019-02-23 12:30
For me work well after use filza tweak in cydia not geo filza and download deb file from pc then transfer to my phone

**Comment by kekrajb** [comment] 2019-02-23 12:39
If you want install Neptune with Cydia: repo.conorthedev.com

**Comment by addtheryan** [comment] 2019-02-23 12:51
Just use @kekrajb repo link . It work
Thanks btw issue closed

**Closed as completed** 2019-03-07 01:43 UTC
