### ISSUE TITLE
Add FaceID padlock

### ISSUE THREAD

**Issue by ghost** [duraidabdul/Neptune#63] opened 2019-02-28 18:19 UTC
Hey could you add FaceID padlock to the lock screen

This tweak https://github.com/SniperGER/ProudLock does that but it's broken on iOS 12.

**Comment by hieurock** [comment] 2019-03-01 01:25
I would like this as well. I like to enable Raise to Wake so that when I raise my phone while my thumb is resting on Touch ID, I can just swipe to unlock. The padlock icon would be satisfying.

**Comment by duraidabdul** [comment] 2019-03-20 22:26
Duplicate of #98

**Closed as completed by duraidabdul** 2019-03-20 22:26 UTC
