### ISSUE TITLE
Add lock icon to cover sheet

### ISSUE THREAD

**Issue by miraged3** [duraidabdul/Neptune#4] opened 2019-02-07 09:42 UTC
Can’t judge the device is locked or not without a lock icon. On iPhone X there’s a big lock icon and on non-notch devices also have a small icon.

**Comment by duraidabdul** [comment] 2019-02-11 01:18
This will be addressed in a future update. The large lock icon will be used.

**Comment by duraidabdul** [comment] 2019-02-11 21:18
Duplicate of #24

**Closed as completed by duraidabdul** 2019-02-11 21:18 UTC
Labels: feature request
