### ISSUE TITLE
Round corners become white when using gif2ani to change the respring screen to something with a white background

### ISSUE THREAD

**Issue by ghost** [duraidabdul/Neptune#75] opened 2019-03-04 15:28 UTC
**Describe the bug**
If you change the respring logo to something with a white background using the tweak gif2ani, the corners become white, as you can see in the following photos.

**Type**
UI bug

**Steps to Reproduce**
Set a white respring background and after a respring corners will become white.

**Expected behavior**
Corners should be black. It would be great to have a switch in the settings to turn rounded corners off.

**Screenshots**
https://share.icloud.com/photos/0E_P9lc-u9pKrru7UUP4wwGBQ

**Information**
 - Device: iPhone 8+
 - iOS Version: iOS 12.1.1 (16C50)
 - Tweak Version: beta 6

**Comment by duraidabdul** [comment] 2019-03-07 01:40
Duplicate of #70

**Closed as completed by duraidabdul** 2019-03-07 01:40 UTC
